// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwfgtopqazimwrwdubec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Zmd0b3BxYXppbXdyd2R1YmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzk0NTEsImV4cCI6MjA3NDcxNTQ1MX0.R-nusWKR7ToPqJPKppRCY1KDqeG3gMEqjNvE2-4rIvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});